### ISSUE TITLE
skunk is failing on pull requests

### ISSUE THREAD

**Issue by etagwerker** [fastruby/skunk.fyi#26]
Not sure why but skunk is returning an error in every PR 😞 

For example: https://github.com/fastruby/skunk.fyi/pull/25

**Comment by etagwerker** [comment]
After further digging, this is related to https://github.com/fastruby/skunk/issues/68 -- There is a new bug in skunk v0.5.0

**Comment by kindoflew** [comment]
hi @etagwerker! can this be closed since fastruby/skunk#69 closed the related issue?

**Comment by etagwerker** [comment]
@kindoflew It can, good point! 💯
