### ISSUE TITLE
It would be great if IDs were alphanumeric and not easy to be guessed

### ISSUE THREAD

**Issue by etagwerker** [fastruby/skunk.fyi#5]
Hey, 

I'm not a big fan of using numeric ids. That is: 

- https://skunk.fastruby.io/1
- https://skunk.fastruby.io/2
- https://skunk.fastruby.io/3
- etc...

I think it would be great if we could automatically generate a slug that is alphanumeric. For example: 

- https://skunk.fastruby.io/d530e56
- https://skunk.fastruby.io/a32f65ab
- etc... 

That way, users could have some privacy in terms of sharing their skunk information. 

URLs would continue to be publicly accessible, but unwanted visitors would have a harder time guessing the slug. 😄 

What do you think?

**Comment by FionaDL** [comment]
@etagwerker looks good to me. It's fine that the slug is really long, right? In the example you only have 6-7 numbers/letters

**Comment by etagwerker** [comment]
@FionaDL yeah, I think that is fine. I assume all people will copy/paste the URL in order to share it. Thanks for testing this!
